DROP PROCEDURE IF EXISTS trimClasspath^;
CREATE PROCEDURE trimClasspath()
BEGIN
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = database() AND TABLE_NAME = 'DATABASECHANGELOG') THEN
        UPDATE DATABASECHANGELOG
        SET FILENAME = TRIM("classpath:" from FILENAME)
        WHERE FILENAME like "classpath:%";
    END IF;
END ^;

CALL trimClasspath^;