INSERT INTO system_role (`name`,`description`) VALUES ('ROLE_USER','A basic user in the system.');
INSERT INTO system_role (`name`,`description`) VALUES ('ROLE_ADMIN','An administrative user in the system.');
INSERT INTO system_role (`name`,`description`) VALUES ('ROLE_CLIENT','A client tool in the system.');
INSERT INTO system_role (`name`,`description`) VALUES ('ROLE_MANAGER','A manager role in the system.');

-- user account required for integration tests
INSERT INTO user (`createdDate`, `modifiedDate`, `email`, `firstName`, `lastName`, `locale`, `password`, `phoneNumber`, `username`, `enabled`, `system_role`, `credentialsNonExpired`) VALUES (now(), now() , 'franklin.bristow@phac-aspc.gc.ca', 'Franklin', 'Bristow', 'en', '$2a$10$yvzFLxWA9m2wNQmHpJtWT.MRZv8qV8Mo3EMB6HTkDnUbi9aBrbWWW', '7029', 'fbristow', 1, 1, 1);
INSERT INTO user (`createdDate`, `modifiedDate`, `email`, `firstName`, `lastName`, `locale`, `password`, `phoneNumber`, `username`, `enabled`, `system_role`, `credentialsNonExpired`) VALUES (now(), now() , 'josh.adam@phac-aspc.gc.ca', 'Josh', 'Adam', 'en', '$2a$10$yvzFLxWA9m2wNQmHpJtWT.MRZv8qV8Mo3EMB6HTkDnUbi9aBrbWWW', '7418', 'josh', 1, 1, 1);
INSERT INTO user (`createdDate`, `modifiedDate`, `email`, `firstName`, `lastName`, `locale`, `password`, `phoneNumber`, `username`, `enabled`, `system_role`, `credentialsNonExpired`) VALUES (now(), now() , 'thomas.matthews@phac-aspc.gc.ca', 'Tom', 'Matthews', 'en', '$2a$10$yvzFLxWA9m2wNQmHpJtWT.MRZv8qV8Mo3EMB6HTkDnUbi9aBrbWWW', '7418', 'tom', 1, 1, 1);
INSERT INTO user (`createdDate`, `modifiedDate`, `email`, `firstName`, `lastName`, `locale`, `password`, `phoneNumber`, `username`, `enabled`, `system_role`, `credentialsNonExpired`) VALUES (now(), now() , 'admin@nowhere.ca', 'Admin', 'Admin', 'en', '$2a$10$yvzFLxWA9m2wNQmHpJtWT.MRZv8qV8Mo3EMB6HTkDnUbi9aBrbWWW', '0000', 'admin', 1, 2, 1);
INSERT INTO user (`createdDate`, `modifiedDate`, `email`, `firstName`, `lastName`, `locale`, `password`, `phoneNumber`, `username`, `enabled`, `system_role`, `credentialsNonExpired`) VALUES (now(), now() , 'test@nowhere.ca', 'Test', 'User', 'en', '$2a$10$yvzFLxWA9m2wNQmHpJtWT.MRZv8qV8Mo3EMB6HTkDnUbi9aBrbWWW', '1234', 'test', 1, 1, 1);
INSERT INTO user (`createdDate`, `modifiedDate`, `email`, `firstName`, `lastName`, `locale`, `password`, `phoneNumber`, `username`, `enabled`, `system_role`, `credentialsNonExpired`) VALUES (now(), now() , 'disabled-guy@nowhere.ca', 'Disabled', 'Guy', 'en', '$2a$10$yvzFLxWA9m2wNQmHpJtWT.MRZv8qV8Mo3EMB6HTkDnUbi9aBrbWWW', '0000', 'disabledguy', 0, 1, 1);
INSERT INTO user (`createdDate`, `modifiedDate`, `email`, `firstName`, `lastName`, `locale`, `password`, `phoneNumber`, `username`, `enabled`, `system_role`, `credentialsNonExpired`) VALUES (now(), now() , 'manager@nowhere.ca', 'Mr.', 'Manager', 'en', '$2a$10$yvzFLxWA9m2wNQmHpJtWT.MRZv8qV8Mo3EMB6HTkDnUbi9aBrbWWW', '1234', 'manager', 1, 2, 1);

-- projects required for integration tests
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 1');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 2');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 3');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 4');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 5');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 6');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 7');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 8');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 9');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 10');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 11');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 12');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 13');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 14');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 15');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 16');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 17');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 18');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 19');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 20');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 21');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 22');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 23');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 24');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 25');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 26');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 27');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 28');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 29');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 30');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 31');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 32');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 33');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 34');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 35');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 36');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 37');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 38');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 39');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 40');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 41');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 42');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 43');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 44');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 45');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 46');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 47');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 48');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 49');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 50');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 51');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 52');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 53');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 54');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 55');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 56');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 57');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 58');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 59');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 60');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 61');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 62');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 63');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 64');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 65');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 66');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 67');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 68');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 69');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 70');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 71');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 72');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 73');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 74');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 75');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 76');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 77');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 78');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 79');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 80');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 81');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 82');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 83');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 84');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 85');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 86');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 87');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 88');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 89');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 90');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 91');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 92');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 93');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 94');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 95');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 96');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 97');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 98');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 99');
INSERT INTO project (`createdDate`, `modifiedDate`, `name`) VALUES (now(), now() , 'Project 100');

-- relationship between projects and users
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 1, 2, 'PROJECT_OWNER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 2, 2, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 3, 2, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 4, 2, 'PROJECT_OWNER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 5, 2, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 6, 2, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 7, 2, 'PROJECT_OWNER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 8, 2, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 9, 2, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 10, 2, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 11, 2, 'PROJECT_OWNER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 12, 2, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 13, 2, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 14, 2, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 1, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 2, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 3, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 4, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 5, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 6, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 7, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 8, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 9, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 10, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 11, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 12, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 13, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 14, 5, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 1, 1, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 2, 1, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 3, 1, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 4, 1, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 5, 1, 'PROJECT_USER');
INSERT INTO project_user (`createdDate`, `project_id`, `user_id`, `projectRole`) VALUES (now(), 100, 1, 'PROJECT_USER');

-- samples
INSERT INTO sample (`createdDate`, `modifiedDate`, `sampleName`, `externalSampleId`, `description`) VALUES (now(), now() , 'Sample 1', 'sample1', 'The first sample');
INSERT INTO sample (`createdDate`, `modifiedDate`, `sampleName`, `externalSampleId`, `description`) VALUES (now(), now() , 'Sample 2', 'sample2', 'The second sample');
INSERT INTO sample (`createdDate`, `modifiedDate`, `sampleName`, `externalSampleId`, `description`) VALUES (now(), now() , 'Sample 3', 'sample3', 'The third sample');
INSERT INTO sample (`createdDate`, `modifiedDate`, `sampleName`, `externalSampleId`, `description`) VALUES (now(), now() , 'Sample 4', 'sample4', 'The fourth sample');
INSERT INTO sample (`createdDate`, `modifiedDate`, `sampleName`, `externalSampleId`, `description`) VALUES (now(), now() , 'Sample 5', 'sample5', 'The fifth sample');
-- sample relationship
INSERT INTO project_sample (`createdDate`, `project_id`, `sample_id`) VALUES (now(), 5, 1);
INSERT INTO project_sample (`createdDate`, `project_id`, `sample_id`) VALUES (now(), 4, 2);
INSERT INTO project_sample (`createdDate`, `project_id`, `sample_id`) VALUES (now(), 4, 3);
INSERT INTO project_sample (`createdDate`, `project_id`, `sample_id`) VALUES (now(), 4, 4);
INSERT INTO project_sample (`createdDate`, `project_id`, `sample_id`) VALUES (now(), 5, 5);