services:
  - mariadb:10.0

stages:
  - test

variables:
  MYSQL_DATABASE: irida_test
  MYSQL_ROOT_PASSWORD: test
  MYSQL_USER: test
  MYSQL_PASSWORD: test
  JDBC_URL: jdbc:mysql://mariadb:3306/irida_test
  TMP_DIRECTORY: /builds/irida
  GALAXY_URL: http://phacnml__galaxy-irida-17.01:80
  GALAXY_INVALID_URL: http://phacnml__galaxy-irida-17.01:48889
  GALAXY_INVALID_URL2: http://phacnml__galaxy-irida-17.01:48890


before_script:
  - mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -hmariadb $MYSQL_DATABASE < ci/irida_latest.sql
  - pushd lib
  - ./install-libs.sh
  - popd

service_job:
#running service layer tests
  tags:
  - docker
  image: docker.corefacility.ca:5000/irida-testing:latest
  script:
  - mvn clean verify -B -Pservice_testing -Djdbc.url=$JDBC_URL -Dirida.it.rootdirectory=$TMP_DIRECTORY
  stage: test
ui_job:
#running ui tests
  tags:
  - docker
  image: docker.corefacility.ca:5000/irida-testing:latest
  script:
  - mvn clean verify -B -Pui_testing -Dwebdriver.chrome.driver=./src/main/webapp/node_modules/chromedriver/lib/chromedriver/chromedriver -Djdbc.url=$JDBC_URL -Dirida.it.nosandbox=true -Dirida.it.headless=true -Dirida.it.rootdirectory=$TMP_DIRECTORY
  stage: test
rest_job:
#running rest api tests
  tags:
  - docker
  image: docker.corefacility.ca:5000/irida-testing:latest
  script:
  - mvn clean verify -Prest_testing -B -Djdbc.url=$JDBC_URL -Dirida.it.rootdirectory=$TMP_DIRECTORY
  stage: test
galaxy_job:
#run initial set of Galaxy tests
  tags:
  - docker
  image: docker.corefacility.ca:5000/irida-testing:latest
  services:
    - mariadb:10.0
    - phacnml/galaxy-irida-17.01:0.17.0-it
  script:
  - mvn clean verify -B -Pgalaxy_testing -Djdbc.url=$JDBC_URL -Dirida.it.rootdirectory=$TMP_DIRECTORY -Dtest.galaxy.url=$GALAXY_URL -Dtest.galaxy.invalid.url=$GALAXY_INVALID_URL -Dtest.galaxy.invalid.url2=$GALAXY_INVALID_URL2
  stage: test
galaxy_pipelines_job:
#lastly, run all Galaxy pipeline-related tests
  tags:
  - docker
  image: docker.corefacility.ca:5000/irida-testing:latest
  services:
    - mariadb:10.0
    - phacnml/galaxy-irida-17.01:0.17.0-it
  script:
  - mvn clean verify -B -Pgalaxy_pipeline_testing -Djdbc.url=$JDBC_URL -Dirida.it.rootdirectory=$TMP_DIRECTORY -Dtest.galaxy.url=$GALAXY_URL -Dtest.galaxy.invalid.url=$GALAXY_INVALID_URL -Dtest.galaxy.invalid.url2=$GALAXY_INVALID_URL2
  stage: test
build-docs_job:
  tags:
  - docker
  image: docker.corefacility.ca:5000/irida-testing:latest
  script: mvn clean site -B
  stage: test
