sudo: required
language: java

env:
  global:
    - "MYSQL_DATABASE=irida_integration_test"
    - "MYSQL_USER=test"
    - "MYSQL_PASSWORD=test"
    - "DB_MAX_WAIT_MILLIS=30000"
  matrix:
    - "TEST_SUITE=galaxy_testing"
    - "TEST_SUITE=galaxy_pipeline_testing"
    - "TEST_SUITE=ui_testing"
    - "TEST_SUITE=doc_testing"
    - "TEST_SUITE=service_testing"
    - "TEST_SUITE=rest_testing"

services:
  - docker
  - mysql

dist: xenial

jdk:
  - openjdk11

rvm:
  - 2.4.1

cache:
  directories:
    - $HOME/.m2

before_install:
  - sudo apt-get install libgconf-2-4

install:
  - mysql -e "CREATE USER '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD'; GRANT ALL ON $MYSQL_DATABASE.* to '$MYSQL_USER'@'localhost';"
  - mvn -version
  - pushd lib; ./install-libs.sh; popd
  - gem install jekyll
  - gem install pygments.rb

script: ./run-tests.sh $TEST_SUITE
