export const LIBRARY_SELECTION_OPTIONS = [
  "RANDOM",
  "PCR",
  "RANDOM PCR",
  "RT-PCR",
  "HMPR",
  "MF",
  "CF-S",
  "CF-M",
  "CF-H",
  "CF-T",
  "MDA",
  "MSLL",
  "cDNA",
  "ChIP",
  "MNase",
  "DNAse",
  "Hybrid Selection",
  "Reduced Representation",
  "Restriction Digest",
  "5-methylcytidine antibody",
  "MBD2 protein methyl-CpG binding domain",
  "CAGE",
  "RACE",
  "size fractionation",
  "Padlock probes capture method",
  "other",
  "unspecified",
];
export const LIBRARY_STRATEGY_OPTIONS = [
  "WGA",
  "WGS",
  "WXS",
  "RNA-Seq",
  "miRNA-Seq",
  "WCS",
  "CLONE",
  "POOLCLONE",
  "AMPLICON",
  "CLONEEND",
  "FINISHING",
  "ChIP-Seq",
  "MNase-Seq",
  "DNase-Hypersensitivity",
  "Bisulfite-Seq",
  "Tn-Seq",
  "EST",
  "FL-cDNA",
  "CTS",
  "MRE-Seq",
  "MeDIP-Seq",
  "MBD-Seq",
  "OTHER",
];
