/*
 * This file renders the OutputFilePreview component for analyses
 */

import React, { Suspense, useContext, useEffect } from "react";
import { Button, Dropdown, Icon, Menu, Tabs } from "antd";
import { AnalysisContext } from "../../../../contexts/AnalysisContext";
import { AnalysisOutputsContext } from "../../../../contexts/AnalysisOutputsContext";

import { TabPaneContent } from "../../../../components/tabs/TabPaneContent";
import { ContentLoading } from "../../../../components/loader/ContentLoading";
import { AnalysisTabularPreview } from "../AnalysisTabularPreview";
import { WarningAlert } from "../../../../components/alerts/WarningAlert";
import { SPACE_XS } from "../../../../styles/spacing";
import { downloadFilesAsZip, downloadOutputFile } from "../../../../apis/analysis/analysis";
import { blue5, grey7 } from "../../../../styles/colors";
import styled from "styled-components";

const ZipDownloadButton = styled(Button)`
  color: ${grey7};

  &:hover {
    color: ${blue5};
  }
`;

const AnalysisTextPreview = React.lazy(() => import("../AnalysisTextPreview"));
const AnalysisJsonPreview = React.lazy(() => import("../AnalysisJsonPreview"));

const { TabPane } = Tabs;

export default function OutputFilePreview() {
  const {
    analysisOutputsContext,
    getAnalysisOutputs,
    jsonExtSet,
    tabExtSet,
    blacklistExtSet
  } = useContext(AnalysisOutputsContext);

  const { analysisContext } = useContext(AnalysisContext);

  useEffect(() => {
    if (analysisOutputsContext.outputs === null) {
      getAnalysisOutputs();
    }
  }, []);

  /*
   * This function gets the menu which is displayed when a user clicks the `...`
   * next to the Download All Files button. This menu has individual download
   * links for each output file generated by the analysis.
   */
  function downloadFilesMenu () {
    let fileNames = [];
    for (const output of analysisOutputsContext.outputs) {
      fileNames.push(<Menu.Item key={output.id}>{output.filename}</Menu.Item>);
    }
    return <Menu onClick={(e) => downloadOutputFile({submissionId: analysisContext.analysis.identifier, fileId: e.key})}>{fileNames}</Menu>;
  }

  /*
   * This function displays the json output preview for json
   * files generated by the analysis.
   */
  function jsonOutputPreview() {
    let jsonOutput = [];

    for (const output of analysisOutputsContext.outputs) {
      if (!output.hasOwnProperty("fileExt") || !output.hasOwnProperty("id")) {
        continue;
      }

      // If the output file ext is json then we create a preview for it
      // and add it to the jsonOutput array
      if (jsonExtSet.has(output.fileExt)) {
        jsonOutput.unshift(
          <AnalysisJsonPreview output={output} key={output.filename} />
        );
      }
    }
    return jsonOutput;
  }

  /*
   * This function displays the tabular output preview for files
   * of tabular type generated by the analysis.
   */
  function tabularOutputPreview() {
    let tabularOutput = [];

    for (const output of analysisOutputsContext.outputs) {
      if (!output.hasOwnProperty("fileExt") || !output.hasOwnProperty("id")) {
        continue;
      }

      // If the output file ext is a tabular type then we create a preview for it
      // and add it to the tabularOutput array
      if (tabExtSet.has(output.fileExt)) {
        tabularOutput.unshift(
          <AnalysisTabularPreview output={output} key={output.filename} />
        );
      }
    }
    return tabularOutput;
  }

  /*
   * This function displays the text output preview for files
   * of textual type (.txt, fasta, etc) generated by the analysis.
   */
  function textOutputPreview() {
    let textOutput = [];

    for (const output of analysisOutputsContext.outputs) {
      if (!output.hasOwnProperty("fileExt") || !output.hasOwnProperty("id")) {
        continue;
      }

      // If the output file ext is not json, tabular, pdf. zip, then we create a preview
      // for it and add it to the textOutput array
      if (!jsonExtSet.has(output.fileExt) && !tabExtSet.has(output.fileExt) && !blacklistExtSet.has(output.fileExt)) {
        textOutput.unshift(
          <AnalysisTextPreview output={output} key={output.filename} />
        );
      }
    }
    return textOutput;
  }

  return analysisOutputsContext.outputs !== null ? (
    <TabPaneContent title={i18n("AnalysisOutputs.outputFilePreview")}>
      {analysisOutputsContext.outputs.length > 0 ? (
        <div>
          <Dropdown.Button id="t-download-all-files-btn" style={{ marginBottom: SPACE_XS }} onClick={() => downloadFilesAsZip(analysisContext.analysis.identifier)} overlay={downloadFilesMenu()}>
              <i
                className="fas fa-file-archive"
                style={{ marginRight: SPACE_XS }}
              ></i>
              {i18n("AnalysisOutputs.downloadAllFiles")}
          </Dropdown.Button>
          <Tabs defaultActiveKey="1" animated={false}>
            {analysisOutputsContext.fileTypes[0].hasTabularFile ? (
              <TabPane
                tab={i18n("AnalysisOutputs.tabularOutput")}
                key="tab-output"
              >
                {tabularOutputPreview()}
              </TabPane>
            ) : null}

            {analysisOutputsContext.fileTypes[0].hasTextFile ? (
              <TabPane
                tab={i18n("AnalysisOutputs.textOutput")}
                key="text-output"
              >
                <Suspense fallback={<ContentLoading />}>
                  {textOutputPreview()}
                </Suspense>
              </TabPane>
            ) : null}

            {analysisOutputsContext.fileTypes[0].hasJsonFile ? (
              <TabPane
                tab={i18n("AnalysisOutputs.jsonOutput")}
                key="json-output"
              >
                <Suspense fallback={<ContentLoading />}>
                  {jsonOutputPreview()}
                </Suspense>
              </TabPane>
            ) : null}
          </Tabs>
        </div>
      ) : (
        <WarningAlert message={i18n("AnalysisOutputs.noOutputsAvailable")} />
      )}
    </TabPaneContent>
  ) : (
    <ContentLoading />
  );
}
